name: Fuel Greeter Indexer
networks:
  - id: 0
    start_block: 0
    contracts:
      - name: Greeter
        address: 0xb9bc445e5696c966dcf7e5d1237bd03c04e3ba6929bdaedfeebc7aae784c3a0b
        abi_file_path: ../contract/sway-contract/out/debug/greeter-abi.json
        handler: ./src/EventHandlers.ts
        events:
          - name: NewGreeting
          - name: ClearGreeting
